name: scTenifoldXct-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip>=23
  - pip:
    - anndata>=0.9
    - cairocffi
    - igraph>=0.10
    - matplotlib>=3.6
    - numpy>=1.23
    - pandas>=1.5
    - ray>=2.0
    - scanpy>=1.9
    - scipy>=1.9
    - statsmodels>=0.13
    - torch>=2.0
    - tqdm>=4.60
    - pytest>=7
    - ruff>=0.1
