site_name: scTenifoldXct
site_description: Predicting cell-cell interactions via manifold learning
repo_url: https://github.com/cailab-tamu/scTenifoldXct
repo_name: cailab-tamu/scTenifoldXct

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: false
            show_root_heading: true
            members_order: source

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
